Nova 5.0 Support
whitecube/nova-flexible-content pull request #530
Opened 2024-12-16 03:36 UTC by bashgeek

Initial attempt at adding Nova 5.0 support.

Builds fine, no more errors. But ran into some upstream vendor JS errors now and don't have time to continue here for now. If anyone else wants to continue or attempt in the meantime, this should give a good starting point.

Would fix #529

2024-12-23 11:41 UTC, crynobone requested changes

2024-12-23 11:41 UTC, crynobone commented on resources/js/components/FormGroup.vue
> +import { mapProps, BehavesAsPanel, Icon } from 'laravel-nova';
```suggestion
import { mapProps, BehavesAsPanel } from 'laravel-nova';
import { Icon } from 'laravel-nova-ui';
```

2024-12-23 11:41 UTC, crynobone commented on package.json
>          "@inertiajs/inertia": "^0.11.0",
```suggestion
```

Provided by `laravel-nova-devtool`

2024-12-23 11:41 UTC, crynobone commented on package.json
>          "laravel-mix": "^6.0.41",
```suggestion
```

Provided by `laravel-nova-devtool`

2024-12-23 11:41 UTC, crynobone commented on package.json
>          "@vue/compiler-sfc": "^3.2.22",
```suggestion
```

Provided by `laravel-nova-devtool`

2024-12-23 11:41 UTC, crynobone commented on composer.json
> +        "laravel/nova-devtool": "^1.0"
```suggestion
        "laravel/nova-devtool": "^1.1.4"
```

Use latest fixes

2024-12-23 11:42 UTC, crynobone commented on package.json
>          "nova:install": "npm --prefix='../../vendor/laravel/nova' ci"
This can be removed

2024-12-23 13:24 UTC, bashgeek commented
@crynobone thanks for you help!

However, the errors coming from vendor.js remain and I still cannot see what's wrong here, maybe another pair of eyes sees it:
```
TypeError: e is undefined
    pi https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    r https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    pi https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    ja https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    I https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    L https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    w https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    F https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    P https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    V https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    w https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    _ https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    V https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    w https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    _ https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    M https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    E https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    w https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    l https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    run https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    runIfDirty https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    gn https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    In https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    promise callback*Sn https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    _n https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    scheduler https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    trigger https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    Ce https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    rt https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    push https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    addGroup https://nova5.test/nova-api/scripts/nova-flexible-content:2
    0 https://nova5.test/nova-api/scripts/nova-flexible-content:2
    gn https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    wn https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    qi https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    addGroup https://nova5.test/nova-api/scripts/nova-flexible-content:2
    onClick https://nova5.test/nova-api/scripts/nova-flexible-content:2
    gn https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    wn https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    n https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    cs https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    ds https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    patchProp https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    A https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    E https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    w https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    B https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    A https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    E https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    w https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    B https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    V https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    w https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    B https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    A https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    E https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    w https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    B https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    A https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    E https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    w https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    _ https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    M https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    E https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    w https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    l https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    run https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    runIfDirty https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    gn https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
    In https://nova5.test/vendor/nova/vendor.js?id=b51081d96a08fc9fb5fe461b8565ac0d:2
vendor.js:2:1139429

```

2024-12-23 13:28 UTC, crynobone commented
@bashgeek can you prepare an example Nova Workbench so I can test this locally, I don't use this package and not familiar with how this can be used.

2024-12-24 05:01 UTC, bashgeek commented
> @bashgeek can you prepare an example Nova Workbench so I can test this locally, I don't use this package and not familiar with how this can be used.

Sure, here: https://github.com/bashgeek/laravel-nova-flexible-test/
I added a test field "content" to the users, which causes the same error as mentioned above when trying to add a section.

Thanks for taking a look at this!

2024-12-24 08:35 UTC, crynobone commented
Submit a PR to fix the issue: https://github.com/blendbyte/nova-flexible-content/pull/1

2024-12-24 14:09 UTC, bashgeek commented
Thanks to @crynobone this is no longer a draft and works fine for me now.

Please note: Breaking change! This will break Nova 4.0 compatibility and only work with Nova 5.0, so please branch out and release a new major version for this.

2025-01-16 09:20 UTC, voidgraphics commented
I'll take a look this week-end, thanks @bashgeek and @crynobone!

2025-01-18 16:50 UTC, voidgraphics commented
Thanks for the PR, looking good on my end, just a couple UI fixes to do but I'll handle those on master because I cannot push to your branch.

2025-01-18 16:51 UTC, merged